language: python
python:
- '3.8'
install:
- python setup.py -q install
script:
- pytest
deploy:
  provider: pypi
  username: "__token__"
  password:
    secure: "UUCmNI/hjYuhVZRt5KMRiNGUeef0BuK764fPV/UwGnpo/4QXoH+1jqWVdUUwdSEF5le04gv4fyvRpkKtZ/rCmeGrceqD9czFD1f1DpyTnsVEzCe7Rn0iHg03U7o3yHeCqR0+m6GmbT9z5QBBv/wcB+9MSVmPgcT+t33xrZFH7A5uWFhWpjSL4EhGnuf7j3GZZpHl3CxhKYJQgUP1ZD45bqeqR5DqvJW23r3KuuDCcTC5acmpj04actXoKqU7NkTZ0QIR7Jg5HwwCUtEHv7NB4EpdrT53/2ez8N7584a1eIe4/U1u64C31PERbxf2ewEZjklWXrEf5C47tU4UiuuW27mI7zPUWPnQ8C2Jetgy1jOzAEyHLkOhOvzfo59Ne38wrLq4AQzWJyF42kDZoUI/ywgEAV+T5dr7J2Qt2uIpMwyEGdQbENDJ2rnIcJw1BkR/5cbbW0ykRdHxIRs06d7iRoJI7TO+sYkat9ED7THITA9fRFyPRjqXKyxKNCONOAYVe3pk+AYhp1eHw2PGMy3e9NK0weK7h3qlcdCLIlfonwcnttHCj5KZzB/EEwVLUy6VOGqoM0LOAP0mWeLz36I9grN3Thc11ge8JWIXD3WLA8spFiFF1/G5/CMnin6dlcxVnmNVZtJyXXOrUHTOU0xjnJsbxBQDiUjDMJCGwicGn1o="
  on:
    tags: true
  skip_existing: true
